title: "Европа Сити - контакты"
description: "2020"
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
resume_avatar:                  "true"
resume_avatar_path:             "images/avatar.png"
resume_name:                    "Европа Сити"
resume_title:                   "Контакты"
resume_header_contact_info:     "Санкт-Петербург"
display_header_contact_info:    "true"
resume_header_intro:            "_"
resume_looking_for_work:        "yes"
resume_section_experience:      true
resume_print_social_links:      false
